language: python

install: pipenv install

python:
    - "3.5"
    - "3.5"
    - "3.6"
    - "3.7"

notifications:
    email:
        - daniel.j.dufour@gmail.com

script: pipenv run python3 -m unittest date_extractor.tests.test
