language: python

python:
    - "2.7"
    - "3.5"
    - "3.5"
    - "3.6"
    - "3.7"

notifications:
    email:
        - daniel.j.dufour@gmail.com

script: python -m unittest date_extractor.tests.test
